CREATE TABLE IF NOT EXISTS task (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    note VARCHAR(300),
    complete BOOLEAN NOT NULL DEFAULT FALSE,
    due_date DATE
    );